version: '3'

services:
  app-1:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=sqlite:///./nodejs/database.db
      
  app-2:
    build:
      context: .
      dockerfile: ./fastapi/Dockerfile
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=sqlite:///./fastapi/users.db

  # db:
  #   image: "sqlite"
  #   volumes:
  #     - ./app/users.db:/usr/src/app/users.db
  #   command: "tail -f /dev/null"
